server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.xssrae.costumer_service.domain"
        spring.json.value.default.type: "com.xssrae.costumer_service.domain.OrderEvent"

app:
  kafka:
    topics:
      orders: orders-topic